version: '3'
services:
  top.api:
    image: docker.pkg.github.com/avolmaxcode/ratings-api/ratings-api:develop
    container_name: ratings-api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env